spring:
  application:
    name: service-registry
server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false