version: '3.8'

services:

  

  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    

  # User Service
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  # Ticket Service
  ticket-service:
    build: ./ticket-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - postgres

  # Admin Service
  admin-service:
    build: ./admin-service
    ports:
      - "8083:8083"
    

  # Notification Service
  notification-service:
    build: ./notification-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka

  # Log Service
  log-service:
    build: ./log-service
    ports:
      - "8085:8085"
    depends_on:
      - mongo
      - kafka

  # SLA Service
  sla-service:
    build: ./sla-service
    ports:
      - "8086:8086"
    depends_on:
      - kafka

  # Tag Service
  tag-service:
    build: ./tag-service
    ports:
      - "8087:8087"
    depends_on:
      - postgres

  # Angular Frontend
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - api-gateway

  # Kafka + Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  # MongoDB
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
