server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/auth/**

        - id: ticket-service
          uri: http://ticket-service:8082
          predicates:
            - Path=/api/tickets/**

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
